### ISSUE TITLE
Not able to use AI features

### ISSUE THREAD

**Issue by siddharthalodha** [UdaraJay/Pile#100]
## Summary

Not able to use any AI features using my own Key

![CleanShot 2024-10-09 at 10 26 00@2x](https://github.com/user-attachments/assets/fc1c0203-4720-4a6a-bba2-7c7244c22cbe)

API settings page

**Comment by jdh08** [comment]
I am experiencing the same issue.

**Comment by UdaraJay** [comment]
things to try:

- make sure you're on the latest version
- make sure the `OpenAI API` tab is selected in setting
- try creating a new oai key and saving it 
- try closing and re-opening the app after setting a key
