### ISSUE TITLE
Ability to change how the time is shown in the timeline.

### ISSUE THREAD

**Issue by Aarekaz** [UdaraJay/Pile#13]
It would be awesome to see the time stamp of when the post were created. A day might have multiple posts and it would be helpful if we can see the time and date. Maybe we can alter the view by clicking on the time stamp.

<img width="114" alt="image" src="https://github.com/UdaraJay/Pile/assets/36888347/c0f020a9-84be-4eaa-919c-262b1a7bf5f1">

**Comment by UdaraJay** [comment]
What could be good is to show the `from now` time for any posts from today, and anything past that gets a standard timestamp (`MMM dd, yyyy hh:mm:ss a` or `MM/dd/yyyy hh:mm:ss a`)

**Comment by Aarekaz** [comment]
Yup, that would be awesome!
