### ISSUE TITLE
Bug: preview generating empty img tag

### ISSUE THREAD

**Issue by khakimov** [UdaraJay/Pile#24]
<img width="1533" alt="image" src="https://github.com/UdaraJay/Pile/assets/396223/0eda70f2-3e6f-4af2-9b5c-6898f49da9cc">

generating empty img tag

```html
<img class="CK_hcajY7MNfGQs9RENC" src="">
```

from here: 

https://github.com/UdaraJay/Pile/blob/2ee06875fe86a0e645eb79e645f29f124fce8d5b/src/renderer/pages/Pile/Editor/LinkPreviews/LinkPreview/index.jsx#L85-L90

easiest way to ```{image && <img src={image} />}```, but showing nothing maybe not the option. Shall we use a pre-set icon(s) for empty/null case...?

**Comment by UdaraJay** [comment]
I noticed this too! I think link icon makes sense in place. feel free to PR it, otherwise I'll fix in the future.
