### ISSUE TITLE
Windows Port?

### ISSUE THREAD

**Issue by parisosuch-dev** [UdaraJay/Pile#25]
I am highly interested in this project, both contributing and using. However, there is no Windows port. I tried cloning the repo and building it myself and found some bugs (hence why this project is not on windows yet). If I can successfully port this to windows, will you accept the contribution? Or are you already working on this yourself.

**Comment by UdaraJay** [comment]
Hey! that would be great! 

If you can PR a fix I'll merge it– it was something to do with writing files using fs that was not working on the windows build when I last looked at it, but that's likely not the only issue. A few folks have asked for a windows version so I'm sure they'd appreciate it too!

**Comment by parisosuch-dev** [comment]
Sounds good! I did notice that `fs` was trying to use unix commands which is why it was throwing errors. Perhaps this is a workaround where we can check what system they are running for certain packages. Along with that, the viewport was a little off. There was no top bar for closing and min-maxing the screen. It was essentially just the screen render minus the window control elements. I will attempt to create a Window's port. Might take some time but will be worthwhile! We should leave this Issue open an reference to anyone other than me that wants to attempt a PR.

**Comment by UdaraJay** [comment]
Thank you! I'll leave this open for now.

**Comment by GTruss** [comment]
Any luck on getting a Windows port? I'm very interested in this project but know very little about migrating code from Unix/Mac to Windows.

**Comment by stardrive7** [comment]
Any news?

**Comment by rllyy97** [comment]
I've created a PR for windows support here => https://github.com/UdaraJay/Pile/pull/42

**Comment by snibo13** [comment]
I had a couple of issues with this when I tried to run it on my system. I've ironed them out but my code is by no means ready for a PR. You can take a look at my WindowsPile repo. The changes mostly revolved around safely handling cases where you don't have an API key included and file management. I'm still trying to set up interoperability with os detection but I don't have a Mac system to double-check.

**Comment by rllyy97** [comment]
@snibo13 I saw these issues with the api key too, they only appear during development and they were present before any of my changes, if you build the app they won't appear.  Still, I've updated my PR with modified error catching logic to avoid some of them as a short-term solution during dev until there's something like an api-unauthenticated state that could be used to just avoid making these requests.

**Comment by GTruss** [comment]
@UdaraJay Now that the Windows PR has been merged, do you want Windows related issues created as new issues or posted in here?

**Comment by UdaraJay** [comment]
Posted here should be fine, because it's electron and the two builds share most of the codebase.

**Comment by UdaraJay** [comment]
Thanks again @rllyy97 for adding this so we can have a Windows build right at the start of a new year! It's appreciated by many!

For anyone checking this: there's a Windows installer as a part of the default release starting v0.9.2 – https://github.com/UdaraJay/Pile/releases/tag/v0.9.2

**Comment by GTruss** [comment]
There's an issue with the Windows default min/max/close buttons covering up the "Reflect" modal window Close button:

![Snag_97244bb8](https://github.com/UdaraJay/Pile/assets/7242661/eb4b5150-89d3-46fc-84eb-924d72c9cc72)

![Snag_97247c8c](https://github.com/UdaraJay/Pile/assets/7242661/e8b165b4-3dd4-4a3d-9808-d9284ef9c3d4)

![Snag_9724b659](https://github.com/UdaraJay/Pile/assets/7242661/5b207658-16ab-4073-b092-98a90a3a56ff)

The big, red close button closes the app not the Reflect modal window.

Using the ESC key will close the Reflect window as a workaround.

**Comment by UdaraJay** [comment]
Thanks for the heads up! Was fixed in the final release :)
