### ISSUE TITLE
Searching entries

### ISSUE THREAD

**Issue by ralfw** [UdaraJay/Pile#28]
A way to search all entries even in a simple way would be great, eg. Cmd+F like in a text editor.

But next level would be a search like the Arc browser is offering: If the search pattern is not found verbatim, then the search phrase is interpreted as a prompt and AI is engaged. With AI posts can be searched semantically.

**Comment by UdaraJay** [comment]
There's a feature for AI search in an upcoming release. Will share it in a new update after some testing.
