### ISSUE TITLE
Make AI responses stand out

### ISSUE THREAD

**Issue by ralfw** [UdaraJay/Pile#29]
Currently an AI response is only marked with a different icon:

<img width="92" alt="image" src="https://github.com/UdaraJay/Pile/assets/132662/1c93d0b3-2d4a-4881-9aca-9988eea125cf">

That's kinda hard to see. AI responses thus do not really stand out. It's not obvious what my contributions are and which ones are from the AI.

I'd like to see either an icon with more contrast/different color or the AI response in a different color (lighter than my own entries).

**Comment by MSR-07** [comment]
If you could provide me with more information, I would be happy to help you solve this issue.

**Comment by ralfw** [comment]
What do you need? It's not a bug; nothing needs to be resolved. Still I'd find it very useful if AI responses where displayed a bit more differently.

Suggestion: give them a different font color.

The design of Pile is pretty beautiful. I like its simplicity. Hence a change needs to be made careful. But I'm sure it can be done without disrupting the overall appearance.

**Comment by UdaraJay** [comment]
this will improve in the future - for now the thread line in replies are a dotted line for AI and solid line for the human.
