### ISSUE TITLE
Divider between days

### ISSUE THREAD

**Issue by ralfw** [UdaraJay/Pile#30]
The calendar on the left is great. A nice, simple design! I like it very much.

But the days clearly distinguished there are not easy to follow in the stream of entries:

<img width="84" alt="image" src="https://github.com/UdaraJay/Pile/assets/132662/d04d61a5-f45c-401f-a324-551d62b4ad87">

Where does a day start/end?

I'd like to see a plain, simple divider line between the last entry of one day and the next.

**Comment by UdaraJay** [comment]
The date on the top now syncs with the entry in view, and the timeline indicates the same day as well.
