### ISSUE TITLE
No dots for yesterday

### ISSUE THREAD

**Issue by ralfw** [UdaraJay/Pile#32]
Today is the 28th. I've written a couple of entries in different threads. Yesterday I did the same.
But now I am confused: the three dots in the timeline are not next to the 27th, but at the current date.

<img width="241" alt="image" src="https://github.com/UdaraJay/Pile/assets/132662/5793b699-8e5e-41b1-b9eb-cf437c87c683">

That's strange. I thought they'd show how many threads (or entries) I created on any given day. And it would be great to see them increase in number even for the current date, when I write more.

**Comment by UdaraJay** [comment]
root cause is #35
