### ISSUE TITLE
Pile not advancing calendar

### ISSUE THREAD

**Issue by ralfw** [UdaraJay/Pile#34]
I kept Pile running since Nov 28th. Today is Nov 29th. This is what I see when I switch to Pile's window today:

<img width="246" alt="image" src="https://github.com/UdaraJay/Pile/assets/132662/22732c4b-5ca8-495b-90c2-1879c8fb3169">

There is no Nov 29th😳 That does not change if I try to scroll upwards.

Once I restart Pile the 29th is shown.

**Comment by UdaraJay** [comment]
root cause is #35 

As an additional note, any upcoming dates will only show when there is at least one entry created in that day.
