### ISSUE TITLE
Auto updating the app with Hazel and Github Releases

### ISSUE THREAD

**Issue by martincik** [UdaraJay/Pile#40]
Hi,

would be cool if the app auto-updates when started or whenever the new release is present notified user.

You could use:
- https://github.com/vercel/hazel
- and here's a bit of code examples: https://www.electronjs.org/docs/latest/tutorial/updates#deploying-an-update-server

This would make the UX much better for the users already having the app installed.

**Comment by UdaraJay** [comment]
Auto updates will be available with the v1.0.0 release.
