### ISSUE TITLE
Windows 11 doesn't work

### ISSUE THREAD

**Issue by zhl111** [UdaraJay/Pile#51]
It crashes as soon as I open it.
## Prerequisites

- [ ] Using npm
- [ ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Current Behavior

![image](https://github.com/UdaraJay/Pile/assets/29135984/c8ca9b84-f472-4bef-8bd8-16cc2ceca54e)

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Node version : 0.92
- electron-react-boilerplate version or branch :
- Operating System and version : win11 10.0.22621 
- Link to your project :

**Comment by GTruss** [comment]
I'm unable to repro the issue in Windows 11. It seems to work when run from VS Code and via the installer. 

Can you post a translation of the message text?
