### ISSUE TITLE
Include OpenAI Hostname Setting?

### ISSUE THREAD

**Issue by Aeonbrk** [UdaraJay/Pile#55]
# Request
- Could you consider adding support for modifying the OpenAI API hostname?
- 
![image](https://github.com/UdaraJay/Pile/assets/88612184/d4df3f33-92be-419b-9aae-e9bf5869b342)

**Comment by UdaraJay** [comment]
that should be doable- can you share the use-case? is it so you can proxy?

**Comment by Aeonbrk** [comment]
Like the project in github called chatgpt next web or something like that which support the mentioned function, allow users to use the proxy. Cause, I'm not in the OpenAI supported country.

**Comment by quan2005** [comment]
mark,  I'm not in the OpenAI supported country, need the `base-api` arguments

**Comment by UdaraJay** [comment]
shipped in latest release (v0.9.3)
