### ISSUE TITLE
Can not write journal for the past dates?

### ISSUE THREAD

**Issue by maxDNA** [UdaraJay/Pile#59]
I tested in mac os (13.6) with the lastest version of the pile.
To my big surprise, it was not possible to change the date for the journal recorded or write a journal for the past dates. 
Did I miss something eg. some shortcut that could pickup specific date while writing?

**Comment by afboyxiyang** [comment]
Yes, you can't add content that doesn't exist, existing content can be modified.

**Comment by UdaraJay** [comment]
doesn't exist atm, but hope to add in the future
