### ISSUE TITLE
Why doesn't Pile use the default macOS shortcut for "hide others"? (command + option + h)?

### ISSUE THREAD

**Issue by hakusaro** [UdaraJay/Pile#61]
Title says it all really. I was trying to "hide others" using command + option + h, but it turns out Pile rebinds this to command + shift + h. Why?

**Comment by UdaraJay** [comment]
if it isn't the default keybind it should be– i'll check and fix it next time I update

**Comment by UdaraJay** [comment]
fixed in latest version (0.9.3) btw :)
