### ISSUE TITLE
Cannot read previously created journals after reinstallation？

### ISSUE THREAD

**Issue by afboyxiyang** [UdaraJay/Pile#65]
Because I reinstalled the software after reinstalling the system, but the original diary created cannot be read, only a new one can be created.
Is it possible to read the old diary document directly

**Comment by UdaraJay** [comment]
if this happens, create a new journal, name it the same as before and for the folder select the parent folder of where old journal is. it will recognize the folder and all the files.

**Comment by afboyxiyang** [comment]
thx

**Comment by afboyxiyang** [comment]
Mac clients and Windows clients cannot implement rereading.
macOS Sonoma 14.3
