### ISSUE TITLE
Not able to open an existing pile

### ISSUE THREAD

**Issue by junyuan-qi** [UdaraJay/Pile#68]
When I click on "open an existing pile", nothing happens.

Expect a file picker is opened, and I can select existing pile folder.

**Comment by NaveenBandarage** [comment]
+1 getting this as well 
<img width="992" alt="image" src="https://github.com/UdaraJay/Pile/assets/37656114/bf2043c3-e16d-4e8b-938d-98be096f7840">

Using 0.9.2 Intel supported dmg.

**Comment by mikewolfxyou** [comment]
Same here, sometimes it happens, so I close the App, then open it again, try to open the Pile file, and wait a little bit, and then it works.

**Comment by UdaraJay** [comment]
Thanks for the heads up! That option should be hidden for now, I missed it on the last build. 

Adding/opening Piles by folder is not a built-in feature yet, but if you're looking to add back a Pile from it's folder it's possible to do so manually. Instructions in #65.
