### ISSUE TITLE
`cmd + V` for pasting images from clipboard. 🙏 

### ISSUE THREAD

**Issue by pawelkontek** [UdaraJay/Pile#8]
`cmd + V` for pasting images from clipboard. 🙏

**Comment by khakimov** [comment]
@pawelkontek its merged today, i've been using it for awhile without problems, let me know if you have any questions and close the issue if everything works 🙌

**Comment by Aarekaz** [comment]
Adding more into it, maybe drag drop images?

**Comment by khakimov** [comment]
> Adding more into it, maybe drag drop images?

done in recent pull request.

**Comment by Aarekaz** [comment]
Thats awesome @khakimov . Can't wait to try it out.
