### ISSUE TITLE
Not able to delete an existing tile

### ISSUE THREAD

**Issue by Aarekaz** [UdaraJay/Pile#9]
## Prerequisites

- [ X ] Using npm
- [ X ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ X ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ X ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ X ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Current Behavior

Can't delete an existing Pile. The whole dialogue box doesn't seem to work. 

## Steps to Reproduce

1. Press the Delete Icon in the pile list

2. It gets stuck

Recording:

https://github.com/UdaraJay/Pile/assets/36888347/af8aec48-42c8-4ae6-a4fa-ce9060d3d694

## Context

Wanted to delete the pile and start a new one. 

## Your Environment

Latest MacOS

**Comment by UdaraJay** [comment]
Fixed in v0.8.0

**Comment by Aarekaz** [comment]
Thanks a lot!
