### ISSUE TITLE
Add support for 

### ISSUE THREAD

**Issue by Welding-Torch** [UdaraJay/Pile#94]
## Summary

[GLHF](https://glhf.chat) (Good Luck Have Fun) lets you easily run (almost) any open-source LLM on autoscaling GPU clusters. It’s free currently.

They have API support and expose an OpenAI compatible API. You can see details when logged in at https://glhf.chat/users/settings/api

Pile should add support for this as it would allow users to have access to **completely free AI features**

I think this could help Pile users **a lot**

LMK if Pile will implement this. Thank you.

**Comment by UdaraJay** [comment]
you can update the base URL to anything that's compatible with the OpenAI v1 API spec and it'll work (needs both completions and embeddings endpoints)

<img width="547" alt="Screenshot 2024-07-26 at 1 11 13 AM" src="https://github.com/user-attachments/assets/e34c134b-33f4-414e-a426-0d84fefbd154">

**Comment by Welding-Torch** [comment]
GLHF states:
Both `/chat/completions` and `/completions` endpoints are available, but it doesn't say anything about `embeddings` endpoints.
